### ISSUE TITLE
a error about loadLanguages()

### ISSUE THREAD

**Issue by Zmoonpie** [PrismJS/prism#1486]
when i update prism from 1.14.0 to 1.15.0,the function loadLanguages(['csharp']) show a error :Cannot find module"."

**Comment by Zmoonpie** [comment]
i find the error in "primsjs/components/index"
```
var pathToLanguages='./prism-'+language
delete require.cache[require.resolve(pathToLanguage)]
```

**Comment by Zmoonpie** [comment]
@mAAdhaTTah

**Comment by mAAdhaTTah** [comment]
Could you provide a reproducible test case?

**Comment by Zmoonpie** [comment]
i find a demo in https://github.com/scfido/codeHighlighter.git

**Comment by Zmoonpie** [comment]
@mAAdhaTTah  can you help me please

**Comment by mAAdhaTTah** [comment]
I can. You're going to have to be patient, as I do this in my free time and haven't had a chance to dive into this yet.

**Comment by Zmoonpie** [comment]
sorry for my rudeness

**Comment by mAAdhaTTah** [comment]
Oh, `loadLanguages` is intended for use in node. For using with webpack, we recommend the [babel plugin](https://github.com/mAAdhaTTah/babel-plugin-prismjs/) ([More details here](https://prismjs.com/#basic-usage)). If you have issues with it, please open an issue in that repo.
